# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#
name: Debug chartpress
on:
  workflow_dispatch:

jobs:
  debug-chartpress:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          # chartpress requires the full history
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # WARNING: Never do this unless you accept exposing credentials to modify
      #          this repo by exposing the GITHUB_TOKEN.
      #
      # action reference: https://github.com/mxschmitt/action-tmate@v3
      - name: To enter a SSH debugging session, read these logs
        uses: mxschmitt/action-tmate@v3
        env:
          GITHUB_TOKEN: "${{ github.token }}"
